---
version: 1
commandUpdated:
  generators:
  - command: kustomize build ./blue/overlays/development
  - command: kustomize build ./red/overlays/development
  - command: kustomize build ./blue/overlays/feature-margin
  - command: kustomize build ./red/overlays/feature-margin
  - command: kustomize build ./blue/overlays/test
  - command: kustomize build ./red/overlays/test
  - command: kustomize build ./blue/overlays/true
  - command: kustomize build ./red/overlays/true
