kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: blue
  namespace: margin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: margin.localhost
    http:
      paths:
      - path: /blue
        backend:
          serviceName: blue
          servicePort: 80
          