---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: feature_branch_1
bases:
- "../../base/"
resources: []
patches: []
patchesJson6902:
- target:
    kind: Ingress
    group: extensions
    version: v1beta1
    name: blue
  path: ingress.yaml
images:
- name: dudo/blue
  newTag: latest
