---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: pull-2-merge
bases:
- "../../base/"
resources: []
patches:
- service.yaml
patchesJson6902:
- target:
    kind: Ingress
    group: extensions
    version: v1beta1
    name: red
  path: ingress.yaml
images: []
