---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namePrefix: stage-
commonLabels:
  app: red
bases:
- ../../base/
patches:
- service_external.yaml
patchesJson6902:
- target:
    kind: Deployment
    group: apps
    version: v1
    name: red
  path: deployment.yaml
- target:
    kind: Ingress
    group: extensions
    version: v1beta1
    name: red
  path: ingress.yaml