---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: feature-margin
bases:
- "../../base/"
resources: []
patches: []
patchesJson6902:
- target:
    kind: Ingress
    group: extensions
    version: v1beta1
    name: red
  path: ingress.yaml
images:
- name: dudo/red
  newTag: 1cedc73
