---
kind: Kustomization
namespace: feature-margin
bases:
- "../../base/"
resources: []
patches:
- service.yaml
patchesJson6902:
- target:
    kind: Ingress
    group: networking.k8s.io
    version: v1beta1
    name: red
  path: ingress.yaml
images: []
