---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: red
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /red
        backend:
          serviceName: red
          servicePort: 80
