---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  annotations:
    flux.weave.works/automated: "true"
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blue
    spec:
      restartPolicy: Always
      containers:
      - resources:
          requests: {}
          limits:
            cpu: 1
            memory: 250M
        imagePullPolicy: Always
        image: dudo/colors:blue-margin
        name: blue
        ports:
        - containerPort: 80
