---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: margin

images:
- name: dudo/blue
  newTag: 00aff0f

resources:
- namespace.yaml

bases:
- ../development

patchesJson6902:
- target:
    kind: Ingress
    group: extensions
    version: v1beta1
    name: blue
  path: ingress.yaml
