---
kind: Kustomization
namespace: feature-margin
bases:
- "../../base/"
resources: []
patches: []
patchesJson6902:
- target:
    kind: Ingress
    group: extensions
    version: v1beta1
    name: blue
  path: ingress.yaml
images:
- name: dudo/blue
  newTag: 45848d3
